services:
  - type: web
    name: sixjd
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: APP_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sixjd-db
          property: connectionString

databases:
  - name: sixjd-db
    plan: free
    databaseName: sixjd
    user: sixjd
