services:
  - type: web
    name: sixjd
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
